# getting latest unbuntu version
FROM ubuntu:latest

# getting apt index update
RUN apt-get update

# Upgade installed software thru apt
RUN apt-get update -y

# Define command to run the package
CMD ["/bin/echo", "Hello, World!"]