version: '3'
services:
  back-end:
    image: task5-softy-pinko-front-end:latest

  front-end:
    image: task5-softy-pinko-front-end:latest
    depends_on:
      - back-end

  proxy:
    image: task5-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end