version: '3'
services:
  softy-pinko-back-end1:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: softy-pinko-back-end1

  softy-pinko-back-end2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: softy-pinko-back-end2

  softy-pinko-front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - softy-pinko-back-end1
      - softy-pinko-back-end2

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - softy-pinko-back-end1
      - softy-pinko-back-end2
    networks:
      - my_network

networks:
  my_network: